---
title: "Time series RMD"
author: "Dori Rathmell"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
```{r}
getwd()
library(tidyverse)
#install.packages(zoo)
library(zoo)
library(lubridate)
#install.packages('trend')
library(trend)
#install.packages('Kendall')
library(Kendall)

timeseries_plottheme <- theme_gray(base_size = 12) +
  theme(axis.text = element_text(color = "Gray"), 
        legend.position = "right")
theme_set(timeseries_plottheme)

Erie_timeseries <- read.csv("./Data/Processed/Erie_2022_processed.csv")

Erie_timeseries$Date <- as.Date(Erie_timeseries$Date, format = '%m/%d/%Y')
class(Erie_timeseries$Date)

Erie_timeseries_1<- 
  Erie_timeseries %>% 
  mutate(Chlorophyll = na.approx(Chla))

Erie_timeseries_1<-Erie_timeseries_1 %>% 
  select('Date','Chlorophyll')

Erie_timeseries_month <-
  Erie_timeseries_1 %>% 
  mutate(Month = month(Date))%>%
  mutate(Year = year(Date)) %>% 
  group_by(Year, Month) %>% 
  summarize(meanchloro = mean(Chlorophyll)) %>% 
              mutate(month_year = my(paste(Month, "-", Year)))

f_month <- month(first(Erie_timeseries_1$Date))
f_year <- year(first(Erie_timeseries_1$Date))
f_day<- day(first(Erie_timeseries_1$Date))
f_month2 <- first(Erie_timeseries_month$Month)
f_year2 <- first(Erie_timeseries_month$Year)

Erie_Daily.ts <- ts(Erie_timeseries_1$Chlorophyll, 
                             start=c(f_year,f_month, f_day),frequency=180) 
Erie_monthly.ts <- ts(Erie_timeseries_month$meanchloro,
                               start=c(f_month2, f_year2),frequency = 3)

Erie_monthly.decomp <- stl(Erie_monthly.ts,s.window = "periodic")
Erie_daily.decomp <-stl(Erie_Daily.ts,s.window = "periodic")

plot(Erie_monthly.decomp)
plot(Erie_daily.decomp)

ChloroOverTime_plot<-
  ggplot(Erie_timeseries_month, aes(x = month_year, y = meanchloro))+
  geom_point()+
  geom_line()+
  timeseries_plottheme+
  ylab('Chloro (ppm)')+
  xlab('Date')
#creating a plot of mean ozone over time 

print(ChloroOverTime_plot)

#pre 2015 timeseries
pre2015_monthly <-
  Erie_timeseries_month %>% filter(Date < '2015-01-01')


